version: "3.8"
services:
  emisor:
    build:
      context: ./emisor
    ports:
      - "5000:5000"
    depends_on:
      - receptor
  receptor:
    build:
      context: ./receptor
    ports:
      - "5001:5001"
